language: php
sudo: false
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer install
  - git config --global user.email "netresearch-kite@example.com"
  - git config --global user.name "Travis CI"